### ISSUE TITLE
Doesn't work on port

### ISSUE THREAD

**Issue by Sofi101** [kvnp/youtune-reactnative#2]
Does n't work on any ports how can i get the backend

**Comment by Sofi101** [comment]
It's not working on port

**Comment by kvnp** [comment]
I assume you use the command `npm run web` to run this project. You propably have something else listening on port 8080. You can change it in webpack.config.js by replacing the line `port: process.env.PORT || 8080,` with `port: 8081,` or any other port you would like to use.

Please post the error message you are receiving if it still doesn't work.

**Comment by Sofi101** [comment]
> I assume you use the command `npm run web` to run this project. You propably have something else listening on port 8080. You can change it in webpack.config.js by replacing the line `port: process.env.PORT || 8080,` with `port: 8081,` or any other port you would like to use.
> 
> Please post the error message you are receiving if it still doesn't work.

The port worked tho

**Comment by kvnp** [comment]
> Don't you need to run the backend the frontend is only working when i run the port
> 

I need more details. What did you do exactly to determine that it's not working?

It sounds like you forgot to change the URL after changing the port.

**Comment by Sofi101** [comment]
So i installed npm then i run npm run web and then the website opens up perfectly but only the frontend which says press home icon to reload

**Comment by Sofi101** [comment]
And the search feature doesn't work either
