### ISSUE TITLE
Not an issue but can the banners be removed for a cleaner look 😀 

### ISSUE THREAD

**Issue by owencz1998** [kvnp/youtune-reactnative#6]
Remove the banners that say home and search 😀

**Comment by kvnp** [comment]
Great timing :D I'm currently playing around with gestures and have been thinking about shrinking the header depending on where the scrollbar is. What do you think about that approach?

**Comment by owencz1998** [comment]
Not a bad idea will there be a test apk soon 😁

**Comment by kvnp** [comment]
Might take a while for that happen as I'm working on implementing everything on Web first. When that is done I will finish Android and iOS :) You can check it out at https://youtune.kvnp.eu/. Things like Casting and Downloads are working on web but not yet on Android. I'll get there soon though. You can always open pull requests if you want to work on it as well :D If have any other suggestions please let me know

**Comment by owencz1998** [comment]
No worries thanks for a quick reply would u like for me to creat a discord group for anyone to join and have sections for feature requests and issue reports I'd like to help out in anyway 😀

**Comment by owencz1998** [comment]
Also is it possible to add a version number on the setting page so when it asks for the reload that it's getting the update if that's not to hard haha sorry to be a pain

**Comment by kvnp** [comment]
> No worries thanks for a quick reply would u like for me to creat a discord group for anyone to join and have sections for feature requests and issue reports I'd like to help out in anyway 😀

That's a great idea! I'd love to join

> Also is it possible to add a version number on the setting page so when it asks for the reload that it's getting the update if that's not to hard haha sorry to be a pain

You are not a pain at all! Thanks for your suggestions :) I think I can do something about it. I think I will let the settings page display a version starting from 0.1 that is incremented with every commit :D

**Comment by owencz1998** [comment]
Excellent mate link to join and I'll make u admin 😁 https://discord.gg/FQqz9SWv

**Comment by owencz1998** [comment]
I'm not much of dev so Iv been learning from a couple of people and like to ask for help but I like to help as much as possible that's all considering I pay for all the bots to help

**Comment by owencz1998** [comment]
Also I don't think this project is still active anymore
